version: '3.8'

services:
  # Central AI Hub for handling requests and routing to specific core team agents
  ai_hub:
    image: rasa/rasa:latest
    container_name: ai_hub
    ports:
      - "5005:5005"  # Main Rasa Hub API port
    networks:
      - omnitide_network
    volumes:
      - /c/omnitidenexus/models/hub:/app/models
      - /c/omnitidenexus/endpoints:/app/endpoints
    command: >
      rasa run --enable-api
      --cors "*"
      --model /app/models
      --endpoints /app/endpoints.yml

  # Core Team NLP Agents
  sherlock_security_ai:
    image: rasa/rasa:latest
    container_name: sherlock_security_ai
    networks:
      - omnitide_network
    volumes:
      - /c/omnitidenexus/models/sherlock:/app/models
    command: >
      rasa run --enable-api
      --model /app/models
      --port 5001

  rick_optimizer_ai:
    image: rasa/rasa:latest
    container_name: rick_optimizer_ai
    networks:
      - omnitide_network
    volumes:
      - /c/omnitidenexus/models/rick:/app/models
    command: >
      rasa run --enable-api
      --model /app/models
      --port 5002

  tony_interface_ai:
    image: rasa/rasa:latest
    container_name: tony_interface_ai
    networks:
      - omnitide_network
    volumes:
      - /c/omnitidenexus/models/tony:/app/models
    command: >
      rasa run --enable-api
      --model /app/models
      --port 5003

  yoda_balancer_ai:
    image: rasa/rasa:latest
    container_name: yoda_balancer_ai
    networks:
      - omnitide_network
    volumes:
      - /c/omnitidenexus/models/yoda:/app/models
    command: >
      rasa run --enable-api
      --model /app/models
      --port 5004

  rocket_security_ai:
    image: rasa/rasa:latest
    container_name: rocket_security_ai
    networks:
      - omnitide_network
    volumes:
      - /c/omnitidenexus/models/rocket:/app/models
    command: >
      rasa run --enable-api
      --model /app/models
      --port 5005

  chainsaw_performance_ai:
    image: rasa/rasa:latest
    container_name: chainsaw_performance_ai
    networks:
      - omnitide_network
    volumes:
      - /c/omnitidenexus/models/chainsaw:/app/models
    command: >
      rasa run --enable-api
      --model /app/models
      --port 5006

  deku_resilience_ai:
    image: rasa/rasa:latest
    container_name: deku_resilience_ai
    networks:
      - omnitide_network
    volumes:
      - /c/omnitidenexus/models/deku:/app/models
    command: >
      rasa run --enable-api
      --model /app/models
      --port 5007

  power_self_repair_ai:
    image: rasa/rasa:latest
    container_name: power_self_repair_ai
    networks:
      - omnitide_network
    volumes:
      - /c/omnitidenexus/models/power:/app/models
    command: >
      rasa run --enable-api
      --model /app/models
      --port 5008

  # Monitoring: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - omnitide_network
    ports:
      - "3000:3000"
    volumes:
      - /c/omnitidenexus/data/grafana:/var/lib/grafana

  # Monitoring: Prometheus for data scraping
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - omnitide_network
    ports:
      - "9090:9090"
    volumes:
      - /c/omnitidenexus/config/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # Command Center Web Interface
  omnitide_dashboard:
    image: omni_dashboard_image
    container_name: omnitide_dashboard
    networks:
      - omnitide_network
    ports:
      - "4000:4000"
    volumes:
      - /c/omnitidenexus/dashboard:/app
    command: "node /app/server.js"

networks:
  omnitide_network:
    driver: bridge
