apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: omnitide-autoscaler
  namespace: omnitidenexus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: omnitide-deployment
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
