version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: omnitide_nginx
    ports:
      - "80:80"   # Accessible on all devices on your network via port 80
    volumes:
      - ./h5ai:/usr/share/nginx/html/_h5ai  # H5AI directory listing
      - ./media:/usr/share/nginx/html/media # Media files directory
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Custom NGINX configuration
    networks:
      - omnitide_network

  php-fpm:
    image: php:7.4-fpm-alpine
    container_name: omnitide_php
    volumes:
      - ./h5ai:/usr/share/nginx/html/_h5ai
      - ./media:/usr/share/nginx/html/media
    networks:
      - omnitide_network

  adminer:
    image: adminer:latest
    container_name: omnitide_adminer
    ports:
      - "8080:8080"  # Access Adminer via http://<server-ip>:8080 for database management
    networks:
      - omnitide_network

networks:
  omnitide_network:
    driver: bridge
